### ISSUE TITLE
About encrypting OTP secrets with the user's password

### ISSUE THREAD

**Issue by aantron** [marcoonroad/twostep#1]
Thanks for this library! @andreypopp is building a full 2FA authentication example based on it (work is [here](https://github.com/andreypopp/dream-totp-auth)).

I'm thinking about some of the issues involved, and I have a question about the secret storage scheme described in the README:

> must be stored encrypted in your servers' databases. A good approach is to encrypt with a KDF on the client password, after you checking the client password against the strongly hashed version on database (prefer 256/512-bits hash algorithms whenever possible, and a KDF in front of this with server's salt is ideal too).

What is the advantage of storing the secrets encrypted with the user's password, rather than the server's master password?

I haven't fully thought through all the implications of either scheme. I am wondering if you could comment based on what you know. I didn't find mention of using the user's password for encryption of the secret in either RFC 4226 (which does mention composite secrets based on the password), or RFC 6238. A brief search found [this post on Stack Exchange](https://security.stackexchange.com/a/24306), but it does not have any references or explanation for the choice of scheme.

**Comment by marcoonroad** [comment]
Hi @aantron,

Sorry for being a bit late, I lost this notification from the inbox.

It's just a recommendation/approach, if the user forgets her password, a reset of the OTP secret would be needed too - together with the link to reset the user's password on her email's inbox (maybe with some secret question, some risky business such as exchanges require a bit of KYC too).

Of course, a master password could be used to encrypt all the OTP secrets, but the security team must ensure proper key management, such as rotating master keys with a predefined window of time, using complex secret sharing/splitting schemes if possible, offloading validations for a host/auto-scale-group listening only over predefined IPs/virtual security group, 24/7 monitoring/alerts against strange behaviors, etc.

Both approaches have their pros and cons, the password-encrypted OTP secret is in risk of data breaches if the user reuses the same password on different sites, while the masterkey-encrypted OTP secret implies a single point-of-failure for the application (which would enable [rights amplification](https://wiki.c2.com/?RightsAmplification) in case of sucessful attacks/compromises).
